version: '3.0'

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.6.0'
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: 'docker.elastic.co/logstash/logstash:6.6.0'
    depends_on:
      - elasticsearch

  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.6.0'
    depends_on:
      - elasticsearch

volumes:
  dbdata:
  esdata: