global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 15s
  external_labels:
    monitor: 'codelab_monitor'


alerting:
  alertmanagers:
  - static_configs:
    - targets: ["localhost:9093"]


rule_files:
  - "rules.yml"


scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9100']
  
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: 'example-random'
    static_configs:
    - targets: ['localhost:8090']
  
  - job_name: 'mysqld'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9104']

  - job_name: 'mysqld-2'
    scrape_interval: 5s
    static_configs:
      - targets: ['188.131.133.107:9104']
        labels:
          instance: cvm001

  - job_name: 'node-2'
    scrape_interval: 5s
    static_configs:
      - targets: ['188.131.133.107:9100']
        labels:
          instance: cvm001

  - job_name: 'redis-2'
    scrape_interval: 5s
    static_configs:
      - targets: ['188.131.133.107:9121']
        labels:
          instance: cvm001

